### ISSUE TITLE
Dimension order bug in SegDataGenerator.py?

### ISSUE THREAD

**Issue by PavlosMelissinos** [aurora95/Keras-FCN#16]
I think there's a bug in the cropping functions. In particular, I believe the correct order should be (h, w) instead of (w, h).

In the constructor, [self.row_index (height) is set to 1 and self.col_index (width) to 2](https://github.com/aurora95/Keras-FCN/blob/master/utils/SegDataGenerator.py#L321-L328). However, in the crop functions, e.g. pair_random_crop, [the width dimension is cropped as the first dimension](https://github.com/aurora95/Keras-FCN/blob/master/utils/SegDataGenerator.py#L64-L67).

Maybe I'm missing something?

**Comment by ahundt** [comment]
I suggest a small test script that loads an image, call the function with obvious parameters like half the height and an eighth the width, write out the result, and post both the original and processed images here... and maybe include the test script too in a pull request haha since it will be needed later if this is to move into keras-contrib

**Comment by PavlosMelissinos** [comment]
Here's the test script

```
from keras.preprocessing.image import img_to_array, array_to_img
from utils import SegDataGenerator
from PIL import Image as PILImage


def test_crop(crop_function):
    filename = 'data/1.jpg'

    img = PILImage.open(filename)

    crop_width = img.width / 5
    crop_height = img.height / 8

    print(crop_height, crop_width)

    img = img_to_array(img)

    result = crop_function(img, (crop_width, crop_height), 'channels_last')
    result = array_to_img(result)

    assert result.width == crop_width
    assert result.height == crop_height


test_crop(SegDataGenerator.center_crop)

test_crop(SegDataGenerator.random_crop)

```

and I've created a jupyter notebook to showcase. You can find it [here](https://gist.github.com/PavlosMelissinos/ec939912231dd72ee52a4bdd99c68d2b)

Do you think this is enough, so that I can add the test and the correct code in a pull request? Mentioning @aurora95 as well.

**Comment by ahundt** [comment]
Yeah I see what you're saying, my usage so far was square so I didn't come across that. Maybe put that code in a `/test/` folder in the pull request with the fix and I'm sure it will be good to merge. :-)

**Comment by PavlosMelissinos** [comment]
I have submitted a PR. Not so sure about the validity of the test though.
