### ISSUE TITLE
I don't get the difference of the network structure between FCN_Resnet50_32s and AtrousFCN_Resnet50_16s

### ISSUE THREAD

**Issue by wtliao** [aurora95/Keras-FCN#29]
Hi,

after analysing the code and comparing the model image, I don't find the difference of the network structure between FCN_Resnet50_32s and AtrousFCN_Resnet50_16s. The only difference is that  AtrousFCN_Resnet50_16s used atrous_identity_block  instead of the original in the last two identity blocks. But I don't get essential difference between atrous_identity_block  and the original one either. As far as I know, the main difference between xxxx_32s and xxx_16s is a skip connection from the 16s downsampling layer to the 32s one. Am I right? Thanks.

**Comment by ahundt** [comment]
sounds about right. Atrous convolution changes the output dimension, it is a pretty simple difference.
