### ISSUE TITLE
如何制作自己得数据集

### ISSUE THREAD

**Issue by xueyingliu** [aurora95/Keras-FCN#36]
您好，用您的代码跑通了pascal voc数据集，现在我想训练自己得数据，数据集标注时候类别和颜色是怎么对应得呀？

**Comment by LokLu** [comment]
Please check the VOC specification, no color is needed. The classes are labeled from 0 to 20

**Comment by xingbotao** [comment]
你跑的是哪个模型呢？我在跑Desnet_FCN时，有一个错误，value_error: cannot feed value of shape(16,320,320,1) for tensor u reshape_1_target:0', which has shape'(?,?)'

**Comment by xueyingliu** [comment]
@xingbotao 我跑的是AtrousFCN_Vgg16_16s，你的错误看起来好象是图片尺寸不符合网络吧，感觉可以改一下target_size什么的

**Comment by zwlshine** [comment]
@xueyingliu 你好，请教一下，我运行的时候总是出错：ValueError: If printing histograms, validation_data must be provided, and cannot be a generator.
而且在函数model.fit_generator（）中验证集validation_data给注释掉了。取消注释也出现这个错误。

**Comment by xueyingliu** [comment]
@zwlshine 这个错误我好像也遇到过，当时觉得是没有必要printing histograms，就把相关的语句给注释掉了。

**Comment by zwlshine** [comment]
@xueyingliu   非常感谢你！整个例子都跑通了。感觉这个错误还想跟tensorflow的一些应用有关系，不过我还没学tensorflow。再次谢谢你。

**Comment by xueyingliu** [comment]
@zwlshine 不客气，一起加油！

**Comment by simonsayshi** [comment]
@xueyingliu 请问target_size代表什么?我跑的时候提示data shape 和label shape不一致，data shape 和设置的target_size是一样的，那么label shape怎么设置？
