### ISSUE TITLE
TypeError: `pad_width` must be of integral type.

### ISSUE THREAD

**Issue by lxyhahaha** [aurora95/Keras-FCN#45]
Hello, thank you for your code.
When I try to run the train.py to do a demo, but I get a "TypeError: `pad_width` must be of integral type.", and it points to the "Keras-FCN\utils\SegDataGenerator.py", line 238, in next
    x = np.lib.pad(x, ((pad_h / 2, pad_h - pad_h / 2), (pad_w / 2, pad_w - pad_w / 2), (0, 0)), 'constant', constant_values=0.)". I don't know how to fix this problem, can you give me some suggestions?

**Comment by WenbinYang123** [comment]
Hello, I got the same problem . I want to know if you have fixed it .  can you give me some suggestion?

**Comment by anas-899** [comment]
@lxyhahaha did you solve the problem?

**Comment by WenbinYang123** [comment]
@anas-899 I solved it by following code:
![image](https://user-images.githubusercontent.com/32453393/31327738-b402a686-ad03-11e7-94f2-0a1328d31afa.png)

**Comment by anas-899** [comment]
@WenbinYang123 
Thanks a lot for your fast response.
I tried your solution and got the following error:
`tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[512]
         [[Node: bn3b_branch2c/moments/mean = Mean[T=DT_FLOAT, Tidx=DT_INT32, keep_dims=true, _device="/job:localhost/replica:0/task:0/gpu:0"](res3b_branch2c/BiasAdd, bn3b_branch2c/moments/mean/reduction_indices)]]
         [[Node: loss/add_53/_2497 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_28257_loss/add_53", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
`
`ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[512]
         [[Node: bn3b_branch2c/moments/mean = Mean[T=DT_FLOAT, Tidx=DT_INT32, keep_dims=true, _device="/job:localhost/replica:0/task:0/gpu:0"](res3b_branch2c/BiasAdd, bn3b_branch2c/moments/mean/reduction_indices)]]
         [[Node: loss/add_53/_2497 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_28257_loss/add_53", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
`

**Comment by anas-899** [comment]
@WenbinYang123  

it turned out that happened because of big batch_size = 16
I changed it to batch_size = 4 and it worked without any problem.

Thanks

**Comment by WenbinYang123** [comment]
@anas-899 you are welcome !  when one epoch has been trianed, I got the  problem, do you know how to fix it ?   

Epoch 1/250
11/12 [==========================>...] - ETA: 1s - loss: 20.4296 - sparse_accuracy_ignoring_last_label: 0.3910Traceback (most recent call last):
  File "train.py", line 232, in <module>
    label_suffix=label_suffix, ignore_label=ignore_label, label_cval=label_cval)
  File "train.py", line 164, in train
    class_weight=class_weight
  File "/usr/local/lib/python3.4/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/training.py", line 2082, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.4/dist-packages/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python3.4/dist-packages/keras/callbacks.py", line 751, in on_epoch_end
    raise ValueError('If printing histograms, validation_data must be '
ValueError: If printing histograms, validation_data must be provided, and cannot be a generator.

**Comment by anas-899** [comment]
@WenbinYang123 
I am getting new error after the training started:

`raise ValueError('If printing histograms, validation_data must be '
ValueError: If printing histograms, validation_data must be provided, and cannot be a generator.`

are you getting same error?

**Comment by WenbinYang123** [comment]
@anas-899 you can change histogram_freq=10 to histogram_freq=0.
![image](https://user-images.githubusercontent.com/32453393/31365474-e769a598-ad9d-11e7-9345-7072a3fef531.png)

**Comment by anas-899** [comment]
@WenbinYang123 
after running the evaluate.py it asked for same error **pad** function in interference.py so I modified it to :
`image = np.lib.pad(image, ((math.ceil(pad_h/2), math.ceil(pad_h - pad_h/2)), (math.ceil(pad_w/2), math.ceil(pad_w - pad_w/2)), (0, 0)), 'constant', constant_values=0.)`

the main problem here it's giving (1, 513, 512, 21) in the output while it should give (1, 512, 512, 21)
if I used floor it will give (1, 511, 512, 21)
If I used int(round()) it will give same as floor.
I will solve it manually by if (==511) condition and replacing it by 512 .. but is there any better solution ?
did you face same problem?

**Comment by jermenkoo** [comment]
@lxyhahaha you seem to be using Python 3 where `/` does floating point division by default; you might want to change that to `//` which performs integral division.

**Comment by lxyhahaha** [comment]
@jermenkoo Thank you, I have just solved it by following your suggest.

**Comment by ahundt** [comment]
Merged a PR that should fix this, let me know if there are still problems, thanks!
