### ISSUE TITLE
"Could not read from remote repository."

### ISSUE THREAD

**Issue by majie19930819** [aurora95/Keras-FCN#46]
When I run  "git clone git@github.com:ahundt/keras-contrib.git -b densenet-atrous"
there is a mistake : 

Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

So I find another keras- contrib ：  git clone https://www.github.com/farizrahman4u/keras-contrib.git

however when i run train.py there is a mistake:
Traceback (most recent call last):
  File "train.py", line 15, in <module>
    from models import *
  File "/home/deeplearning/src/Keras-FCN/models.py", line 6, in <module>
    from keras_contrib.applications import densenet
  File "build/bdist.linux-x86_64/egg/keras_contrib/__init__.py", line 13, in <module>
  File "build/bdist.linux-x86_64/egg/keras_contrib/optimizers/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/keras_contrib/optimizers/ftml.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/keras_contrib/optimizers/ftml.py", line 34, in FTML
AttributeError: 'module' object has no attribute 'legacy_get_updates_support'

**Comment by Pan-zhaoyu** [comment]
I meet the same problem with you. Have you already solved it?

**Comment by Pan-zhaoyu** [comment]
Hey, I solved the problem according to this website  http://blog.csdn.net/jingtingfengguo/article/details/51892864
Hope it will help you!

**Comment by ahundt** [comment]
Glad you solved it! FYI densenet is super slow on tensorflow due to https://github.com/tensorflow/tensorflow/issues/12948, so I don't use it.

**Comment by mortezap91** [comment]
hi 2 all
I just want to write the mentioned code in zsh terminal and i use  git clone https://www.github.com/farizrahman4u/keras-contrib.git for keras and download the https://github.com/ahundt/tf-image-segmentation/tree/ahundt-keras for tensorflow part but while I run the pyhton data_coco.py I get an error zsh: illegal hardware instruction  python data_coco.py coco_setup and I don't know .could someone help me ?? I stuck on this
