### ISSUE TITLE
 File "/usr/local/lib/python3.5/dist-packages/keras_contrib-1.2.1-py3.5.egg/keras_contrib/backend/tensorflow_backend.py", line 10, in <module> ImportError: cannot import name '_postprocess_conv3d_output'

### ISSUE THREAD

**Issue by OrdinaryChen** [aurora95/Keras-FCN#53]
The code raise this error when I try "python train.py "
but I check the egg file and found the "from keras.backend.tensorflow_backend import _postprocess_conv3d_output" in line10.  so I try to use print(dir()) to show what this module contains.
but I can only see _preprocess_conv2d_input', '_preprocess_conv3d_input', '_preprocess_padding',
there is no function named _postprocess_conv3d_output 
How can it be?

**Comment by tomonari-t** [comment]
@OrdinaryChen 
I had same problem. It causes [keras-contrib](https://github.com/farizrahman4u/keras-contrib/issues/164).

I fixed the problem to make Keras version to 2.0.8 by pip.

`pip install Keras==2.0.8`

**Comment by ahundt** [comment]
yeah need to use keras 2 now
