### ISSUE TITLE
model.py assumes weights file exists

### ISSUE THREAD

**Issue by ahundt** [aurora95/Keras-FCN#7]
It seems [models.py](https://github.com/aurora95/Keras-FCN/blob/master/models.py#L208) assumes a weights file exists. With the repository as is it doesn't, did you initialize with imagenet weights or something or simply comment those lines the first time you run?

**Comment by SCP-173-cool** [comment]
you can review the `utils/get_weights_path.py ` and `utils/transfer_FCN.py `

**Comment by ahundt** [comment]
Thanks looks clear enough
