### ISSUE TITLE
models.py

### ISSUE THREAD

**Issue by jingdanyang6967634** [aurora95/Keras-FCN#72]
hello,this is problem about keras
this is code about six row
from keras_contrib.applications import densenet

**ModuleNotFoundError: No module named 'keras_contrib'**

How import this model  densenet？

**Comment by zy937085318** [comment]
I meet the same question, anybody know how to handle it? The answer from [https://github.com/keras-team/keras-contrib/issues/164](url) is to copy the function from a previous version of keras which included it. Does anyone know how can I find previous keras?

**Comment by IndustrialCodeWorm** [comment]
Will you solve this problem? I have also encountered this problem.

**Comment by chinmayshah99** [comment]
It is already solved on [stackoverflow](https://stackoverflow.com/questions/49791178/importerror-no-module-named-keras-contrib)
Hope this solves your problem @IndustrialCodeWorm @jingdanyang :)
