### ISSUE TITLE
Strange results from inference.py

### ISSUE THREAD

**Issue by cemsaz** [aurora95/Keras-FCN#76]
After I installed keras-contrib and downloaded PASCAL VOC 2012-berkeley augmented Pascal VOC, I ran the inference.py. I got very strange results. Anyone had this problem?
Input image:
![2007_000363](https://user-images.githubusercontent.com/11336887/39998338-c3978b8e-5753-11e8-9c64-c8bc80502706.jpg)

Output:
![2007_000363](https://user-images.githubusercontent.com/11336887/39998353-d3461d3e-5753-11e8-9331-ec7a077e0305.png)

**Comment by JCamiloB21** [comment]
Do you found any solutiond

**Comment by JCamiloB21** [comment]
did you found any solution?
